const VACANCY_INFORMATION_MODEL = {
  FETCH_VACANCY_INQUIRY_INFO_LOADING: "FETCH_VACANCY_INQUIRY_INFO_LOADING",
  FETCH_VACANCY_INQUIRY_INFO_SUCCESS: "FETCH_VACANCY_INQUIRY_INFO_SUCCESS",
  FETCH_VACANCY_INQUIRY_INFO_ERROR: "FETCH_VACANCY_INQUIRY_INFO_ERROR"
};

export default VACANCY_INFORMATION_MODEL;
