import ROOM_INFORMATION_MODEL from "./roomInformation";

const RESERVATION_MODEL = {
  REGISTER_RESERVATION_LOADING: "REGISTER_RESERVATION_LOADING",
  REGISTER_RESERVATION_SUCCESS: "REGISTER_RESERVATION_SUCCESS",
  REGISTER_RESERVATION_ERROR: "REGISTER_RESERVATION_ERROR",
  ...ROOM_INFORMATION_MODEL
};

export default RESERVATION_MODEL;
