export default {
  reserve: {
    id: 70,
    reserveNo: "0000045",
    reserveBranchNumber: "000",
    reserveLabelId: null,
    reserveLabelRepresentDiv: null,
    remark: "共通備考",
    registerStoreCode: "001",
    registerUserId: "test@usen-next.jp",
    registerDateTime: "2019-11-30T15:00:00Z",
    updateStoreCode: "001",
    updateUserId: "test@usen-next.jp",
    updateDateTime: "2019-11-30T15:00:00Z",
    deleteDiv: "1"
  },
  reserveDaily: [
    {
      id: 337,
      reserveId: 70,
      reserveDate: "2019-12-05",
      reserveDiv: "1",
      roomTypeCode: "6",
      stayPlanCode: "001",
      reservePersonId: 64,
      reserveRouteCode: "001",
      paymentCode: "1",
      arrivalTimeHour: 9,
      arrivalTimeMinute: 0,
      personNo: 1,
      remark: "明細備考01",
      checkInTime: null,
      checkOutTime: null,
      netReserveId: null,
      netRemark: "ネット備考",
      registerStoreCode: "001",
      registerUserId: "test@usen-next.jp",
      registerDateTime: "2019-11-30T15:00:00Z",
      updateStoreCode: "001",
      updateUserId: "test@usen-next.jp",
      updateDateTime: "2019-11-30T15:00:00Z",
      deleteDiv: "1"
    },
    {
      id: 338,
      reserveId: 70,
      reserveDate: "2019-12-06",
      reserveDiv: "1",
      roomTypeCode: "6",
      stayPlanCode: "001",
      reservePersonId: 64,
      reserveRouteCode: "001",
      paymentCode: "1",
      arrivalTimeHour: 9,
      arrivalTimeMinute: 0,
      personNo: 1,
      remark: "明細備考01",
      checkInTime: null,
      checkOutTime: null,
      netReserveId: null,
      netRemark: "ネット備考",
      registerStoreCode: "001",
      registerUserId: "test@usen-next.jp",
      registerDateTime: "2019-11-30T15:00:00Z",
      updateStoreCode: "001",
      updateUserId: "test@usen-next.jp",
      updateDateTime: "2019-11-30T15:00:00Z",
      deleteDiv: "1"
    }
  ],
  reservePerson: {
    id: 64,
    memberNo: "1",
    reservePersonName: "テスト00",
    reservePersonNameKana: null,
    nationality: null,
    sexDiv: null,
    corporationName: "株式会社 アルメックス",
    corporationNameKana: null,
    telNo: "03-6895-1472",
    mobilePhoneNo: "090-1234-5678",
    faxNo: "03-3842-7573",
    emailAddress: "test@usen-next.jp",
    registerStoreCode: "001",
    registerUserId: "test@usen-next.jp",
    registerDateTime: "2019-11-30T15:00:00Z",
    updateStoreCode: "001",
    updateUserId: "test@usen-next.jp",
    updateDateTime: "2019-11-30T15:00:00Z",
    deleteDiv: "1"
  },
  reserveGuest: [
    {
      id: 337,
      reserveDailyId: 337,
      memberNo: "1",
      guestDiv: "1",
      guestName: "のび太",
      guestNameKana: null,
      adultDiv: null,
      nationality: null,
      sexDiv: null,
      corporationName: null,
      corporationNameKana: null,
      telNo: null,
      mobilePhoneNo: null,
      faxNo: null,
      emailAddress: null,
      registerStoreCode: "001",
      registerUserId: "test@usen-next.jp",
      registerDateTime: "2019-11-30T15:00:00Z",
      updateStoreCode: "001",
      updateUserId: "test@usen-next.jp",
      updateDateTime: "2019-11-30T15:00:00Z",
      deleteDiv: "1"
    },
    {
      id: 338,
      reserveDailyId: 338,
      memberNo: "1",
      guestDiv: "1",
      guestName: "のび太",
      guestNameKana: null,
      adultDiv: null,
      nationality: null,
      sexDiv: null,
      corporationName: null,
      corporationNameKana: null,
      telNo: null,
      mobilePhoneNo: null,
      faxNo: null,
      emailAddress: null,
      registerStoreCode: "001",
      registerUserId: "test@usen-next.jp",
      registerDateTime: "2019-11-30T15:00:00Z",
      updateStoreCode: "001",
      updateUserId: "test@usen-next.jp",
      updateDateTime: "2019-11-30T15:00:00Z",
      deleteDiv: "1"
    }
  ]
};
